# Generated by Django 4.1.7 on 2023-03-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember_Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='core.crewmember')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='core.flight')),
            ],
        ),
    ]
