# Generated by Django 4.1.7 on 2023-03-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crewmember_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number',
            field=models.CharField(default='146789', max_length=10),
            preserve_default=False,
        ),
    ]
