# Generated by Django 4.1.7 on 2023-03-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='core.aircraft'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flights_arrive', to='core.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flights_depart', to='core.airport'),
            preserve_default=False,
        ),
    ]
